version: '3.3'
services:
    chatgpt-proxy:
        build: .
        image: chatgpt-proxy-v4
        container_name: chatgpt-proxy-v4
        ports:
            - '8090:8090'
        env_file:
            - .env